// <auto-generated />
namespace OSBOX.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_type_to_folder_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_type_to_folder_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201410121542502_add_type_to_folder_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
