// <auto-generated />
namespace OSBOX.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class servicetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(servicetype));
        
        string IMigrationMetadata.Id
        {
            get { return "201502142113163_servicetype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
