// <auto-generated />
namespace OSBOX.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ServiceTypeIDINInvoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ServiceTypeIDINInvoice));
        
        string IMigrationMetadata.Id
        {
            get { return "201502170339271_ServiceTypeIDINInvoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
